apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-allowed
  labels:
    app: nginx-privilege-escalation
spec:
  containers:
  - name: nginx
    image: nginx:1.24
    securityContext:
      allowPrivilegeEscalation: false