apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- allow-privilege-escalation/template.yaml
- allow-privilege-escalation/constraint.yaml
- privileged-containers/template.yaml
- privileged-containers/constraint.yaml
- tag/template.yaml
- tag/constraint.yaml
- run-as-non-root/template.yaml
- run-as-non-root/constraint.yaml

namespace: gatekeeper-system